### ISSUE TITLE
Logger error on 2.7.2

### ISSUE THREAD

**Issue by morgoth** [bensheldon/good_job#463]
I'm getting an error after gem upgrade and during assets precompilation:

```
#> rails assets:precompile
rails aborted!
NoMethodError: undefined method `logger' for {:execution_mode=>:external, :poll_interval=>1, :shutdown_timeout=>25}:Hash
/home/wojtek/Projects/tiramizoo/trmz/config/environment.rb:5:in `<main>'
```

I setup GJ via initializer:
```
require "active_job_error_handler"

GoodJob.preserve_job_records = :on_unhandled_error
GoodJob.retry_on_unhandled_error = false
GoodJob.active_record_parent_class = "ApplicationRecord"

ActionMailer::MailDeliveryJob.include(ActiveJobErrorHandler)
```

and environments/develoment.rb:
```
  config.active_job.queue_adapter = :good_job
  config.good_job = {execution_mode: :external, poll_interval: 1, shutdown_timeout: 25}
```

There is also in my application.rb: `require "good_job/engine"`

It is working fine on 2.7.1

**Comment by bensheldon** [comment]
@morgoth aha! I can fix that momentarily. Caused by this: #460

**Comment by bensheldon** [comment]
Fix released in [GoodJob `v2.7.3`](https://github.com/bensheldon/good_job/releases/tag/v2.7.3)
